hw6/hasker/api/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token

from . import views


app_name = 'api'
urlpatterns = [
    url(r'^$', views.api_root),
    url(r'^questions/$', views.QuestionList.as_view(), name='question-list'),
    url(r'^questions/(?P<pk>[0-9]+)$', views.QuestionDetail.as_view(), name='question-detail'),
    url(r'^questions/(?P<pk>[0-9]+)/answers/$', views.AnswerList.as_view(), name='answer-list'),
    url(r'^trending/$', views.TopQuestionList.as_view(), name='trending-list'),
    url(r'^search/$', views.SearchList.as_view(), name='search-list'),
    url(r'^token-auth/$', obtain_jwt_token, name='token-auth'),
    url(r'^token-refresh/$', refresh_jwt_token, name='token-refresh'),
    url(r'^token-verify/$', verify_jwt_token, name='token-verify'),
]

hw6/hasker/askme/urls.py
from django.conf.urls import url

from . import views


app_name = 'askme'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^ask/$', views.ask, name='ask'),
    url(r'^question/(.+)/$', views.question_detail, name='question'),
    url(r'^tag/(.+)/$', views.search_tag, name='search_tag'),
    url(r'^search/$', views.search, name='search'),
    url(r'^api_common/answer/setcorrect/([0-9]+)/$', views.set_correct_answer, name='set_correct'),
    url(r'^api_common/answer/voteup/([0-9]+)/$', views.answer_vote_up),
    url(r'^api_common/answer/votedown/([0-9]+)/$', views.answer_vote_down),
    url(r'^api_common/question/voteup/([0-9]+)/$', views.question_vote_up),
    url(r'^api_common/question/votedown/([0-9]+)/$', views.question_vote_down),
]

hw6/hasker/hasker/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

# from django.contrib.auth import get_user_model
# from rest_framework import serializers, viewsets, routers
#
# from api.views import QuestionViewSet
#
# User = get_user_model()
#
#
# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = User
#         fields = ('username', 'email')
#
#
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer
#
#
# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)
# router.register(r'questions', QuestionViewSet)


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('askme.urls')),
    url(r'^', include('hasker_user.urls')),
    # url(r'^api/v1/', include(router.urls)),
    url(r'^api/v1/', include('api.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hw6/hasker/hasker_user/urls.py
from django.conf.urls import url

from . import views


app_name = 'hasker_user'
urlpatterns = [
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^settings/$', views.settings, name='settings'),
    url(r'^signup/$', views.signup, name='signup'),
]

hw6/hasker/askme/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, transaction
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from django.forms import ModelForm


User = get_user_model()


class Tag(models.Model):
    name = models.CharField(max_length=20, unique=True)


class Question(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_pub = models.DateField(auto_now_add=True)
    slug = models.SlugField(unique=True)
    user = models.ForeignKey(User)
    tags = models.ManyToManyField(Tag)
    votes = models.IntegerField(default=0)
    correct_answer = models.ForeignKey('Answer', null=True, blank=True, related_name='correct_answer')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            # todo решить проблему одинаковых title
        super(Question, self).save(*args, **kwargs)

    @transaction.atomic
    def vote_up(self, user_id):
        vote = self.uservote_set.filter(user_id=user_id).first()
        if not vote:
            self._add_vote(user_id, 1)
        elif vote and vote.value < 0:
            self._revert_vote(vote, 1)

    @transaction.atomic
    def vote_down(self, user_id):
        vote = self.uservote_set.filter(user_id=user_id).first()
        if not vote:
            self._add_vote(user_id, -1)
        elif vote and vote.value > 0:
            self._revert_vote(vote, -1)

    def _add_vote(self, user_id, value):
        self.uservote_set.create(user_id=user_id, question_id=self.pk, value=value)
        self.votes += value
        self.save()

    def _revert_vote(self, vote, value):
        vote.delete()
        self.votes += value
        self.save()


class Answer(models.Model):
    text = models.TextField()
    date = models.DateField(auto_now_add=True)
    question = models.ForeignKey(Question)
    user = models.ForeignKey(User)
    votes = models.IntegerField(default=0)

    @transaction.atomic
    def vote_up(self, user_id):
        vote = self.uservote_set.filter(user_id=user_id).first()
        if not vote:
            self._add_vote(user_id, 1)
        elif vote and vote.value < 0:
            self._revert_vote(vote, 1)

    @transaction.atomic
    def vote_down(self, user_id):
        vote = self.uservote_set.filter(user_id=user_id).first()
        if not vote:
            self._add_vote(user_id, -1)
        elif vote and vote.value > 0:
            self._revert_vote(vote, -1)

    def _add_vote(self, user_id, value):
        self.uservote_set.create(user_id=user_id, answer_id=self.pk, value=value)
        self.votes += value
        self.save()

    def _revert_vote(self, vote, value):
        vote.delete()
        self.votes += value
        self.save()

    def is_correct(self):
        return self.question.correct_answer.pk == self.pk


class UserVote(models.Model):
    user = models.ForeignKey(User)
    value = models.IntegerField()  # -1 or 1
    answer = models.ForeignKey(Answer, blank=True, null=True, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, blank=True, null=True, on_delete=models.CASCADE)

hw6/hasker/askme/forms.py
# coding=utf8
from django import forms


class MultiTagField(forms.Field):
    def to_python(self, value):
        if not value:
            return []
        value = value.strip()
        if ',' in value:
            sep = ','
        else:
            sep = ' '
        return [s.strip() for s in value.split(sep)]


class QuestionForm(forms.Form):
    title = forms.CharField(max_length=200)
    text = forms.CharField(widget=forms.Textarea)
    tags = MultiTagField(required=False)

    def clean_tags(self):
        tags = self.cleaned_data.get('tags', [])
        if len(tags) > 3:
            raise forms.ValidationError('Количество тегов должно быть не более трех')
        return tags

hw6/hasker/askme/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import transaction
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest
from django.urls import reverse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.decorators.http import require_POST, require_safe, require_http_methods
from django.contrib.auth import get_user_model
from django.contrib.postgres.search import SearchVector

from .forms import QuestionForm
from .models import Question, Tag, Answer


User = get_user_model()


@require_safe
def index(request):
    questions_list = Question.objects.all().order_by('-date_pub', '-votes')
    page = request.GET.get('page')
    questions = paginate(questions_list, page)
    return render(request, 'askme/index.html', {
        'questions': questions
    })


def ask(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            quest_params = {
                'title': cd['title'],
                'text': cd['text'],
                'user_id': request.user.pk
            }
            with transaction.atomic():
                question = Question.objects.create(**quest_params)
                if cd.get('tags'):
                    tag_names = cd['tags']
                    tags = []
                    for tag_name in tag_names:
                        tag, _ = Tag.objects.get_or_create(name=tag_name)
                        tags.append(tag)
                    question.tags.add(*tags)
            return HttpResponseRedirect('/')
    else:
        # Создаем пустую форму Question и отдаем ее в шаблон
        form = QuestionForm()
    return render(request, 'askme/ask.html', {
        'form': form,
        'hide_ask_btn': True
    })


@require_http_methods('POST, GET')
def question_detail(request, slug):
    question = get_object_or_404(Question, slug=slug)
    if request.method == 'POST':
        # Добавим ответ к этому вопросу
        answer_text = request.POST.get('text')
        if answer_text:
            if request.user.is_authenticated:
                question.answer_set.create(text=answer_text, user=request.user)
                # todo send email to author of question
                return HttpResponseRedirect(reverse('askme:question', args=(slug,)))

    answer_list = question.answer_set.all().order_by('-votes')
    page = request.GET.get('page')
    answers = paginate(answer_list, page, 30)
    return render(request, 'askme/question.html', {
        'question': question,
        'answers': answers
    })


def search_tag(request, tag_name):
    tag = Tag.objects.filter(name=tag_name).first()
    if tag:
        questions_list = tag.question_set.all()
    else:
        questions_list = []
    page = request.GET.get('page')
    questions = paginate(questions_list, page)
    return render(request, 'askme/search.html', {
        'questions': questions,
        'head_title': 'Tag results',
        'search_query': 'tag:{}'.format(tag_name)
    })


@require_safe
def search(request):
    query = request.GET.get('q') or ''
    if len(query) > 100:
        # query too long. Return nothing
        questions_list = []
    else:
        questions_list = Question.objects.annotate(
            search=SearchVector('title', 'text')
        ).filter(search=query).all().order_by('-date_pub', '-votes')
    page = request.GET.get('page')
    questions = paginate(questions_list, page)
    return render(request, 'askme/search.html', {
        'questions': questions,
        'head_title': 'Search results'
    })


def answer_vote(request, answer_id, to_up):
    if not request.user.is_authenticated:
        return HttpResponseBadRequest()
    answer = Answer.objects.filter(pk=answer_id).first()
    if not answer:
        return HttpResponseBadRequest()

    user_id = request.user.pk
    if to_up:
        answer.vote_up(user_id)
    else:
        answer.vote_down(user_id)

    return HttpResponse(answer.votes)  # total votes


@require_POST
def answer_vote_up(request, answer_id):
    return answer_vote(request, answer_id, to_up=True)


@require_POST
def answer_vote_down(request, answer_id):
    return answer_vote(request, answer_id, to_up=False)


def question_vote(request, question_id, to_up):
    if not request.user.is_authenticated:
        return HttpResponseBadRequest()
    question = Question.objects.filter(pk=question_id).first()
    if not question:
        return HttpResponseBadRequest()

    user_id = request.user.pk
    if to_up:
        question.vote_up(user_id)
    else:
        question.vote_down(user_id)

    # Возвращаем общее кол-во голосов
    return HttpResponse(question.votes)


@require_POST
def question_vote_up(request, question_id):
    return question_vote(request, question_id, True)


@require_POST
def question_vote_down(request, question_id):
    return question_vote(request, question_id, False)


@require_POST
def set_correct_answer(request, answer_id):
    if not request.user.is_authenticated:
        return HttpResponseBadRequest()

    answer = Answer.objects.filter(pk=answer_id).first()
    if not answer:
        return HttpResponseBadRequest()

    answer.question.correct_answer = answer
    answer.question.save()
    return HttpResponse(answer.question.correct_answer_id)


def paginate(entity_list, page, per_page=20):
    paginator = Paginator(entity_list, per_page)
    try:
        entities = paginator.page(page)
    except PageNotAnInteger:
        entities = paginator.page(1)
    except EmptyPage:
        entities = paginator.page(paginator.num_pages)
    return entities

hw6/hasker/askme/templates/askme/answer_row.html
<div class="row">
    <div class="col text-center">
        <h6>{{ question.votes }}</h6>
        <p>Votes</p>
    </div>
    <div class="col text-center">
        <h6>{{ question.answer_set.count }}</h6>
        <p>Answers</p>
    </div>
    <div class="col-sm-4">
        <a href="{% url 'askme:question' question.slug %}">{{ question.title }}</a>
        <br>
        {% for tag in question.tags.all %}
            <a class="badge badge-primary" href="{% url 'askme:search_tag' tag.name %}">{{ tag.name }}</a>
        {% endfor %}
    </div>
    <div class="col col-sm-4">
        <img src="{{ question.user.photo_url }}" alt="" height="30px">
        <span>{{ question.user.username }}</span>
        <div>Asked {{ question.date_pub|timesince }} ago</div>
    </div>
</div>
<hr>

hw6/hasker/askme/templates/askme/ask.html
{% extends "askme/base.html" %}

{% block content %}
    <h2>Ask a question</h2>
    <form action="" method="post">
        {% csrf_token %}

        <div class="form-group row h5">
            <label for="{{ form.title.id_for_label }}" class="col-sm-3 col-form-label">Title</label>
            <div class="col-sm-4">
                <input name="title"
                       id="{{ form.title.id_for_label }}"
                       type="text"
                       class="form-control {% if form.title.errors %} is-invalid {% endif %}"
                       value="{{ form.title.value|default:'' }}"
                       placeholder="Title">
                {% if form.title.errors %}
                    <div class="invalid-feedback">{{ form.title.errors.0 }}</div>
                {% endif %}
            </div>
        </div>
        <div class="form-group row h5">
            <label for="{{ form.text.id_for_label }}" class="col-sm-3 col-form-label">Text</label>
            <div class="col-sm-4">
                <textarea name="text"
                          id="{{ form.text.id_for_label }}"
                          class="form-control {% if form.text.errors %} is-invalid {% endif %}"
                          placeholder="Text"
                          rows="10">{{ form.text.value|default:'' }}</textarea>
                {% if form.text.errors %}
                    <div class="invalid-feedback">{{ form.text.errors.0 }}</div>
                {% endif %}
            </div>
        </div>
        <div class="form-group row h5">
            <label for="{{ form.tags.id_for_label }}" class="col-sm-3 col-form-label">Tags</label>
            <div class="col-sm-4">
                <input name="tags"
                       id="{{ form.tags.id_for_label }}"
                       type="text"
                       class="form-control {% if form.tags.errors %} is-invalid {% endif %}"
                       value="{{ form.tags.value|default:'' }}"
                       placeholder="Title">
                {% if form.tags.errors %}
                    <div class="invalid-feedback">{{ form.tags.errors.0 }}</div>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-secondary">Enter</button>
            </div>
        </div>
    </form>

{% endblock %}

hw6/hasker/askme/templates/askme/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static "askme/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "askme/css/bootstrap-grid.min.css" %}">
    <link rel="stylesheet" href="{% static "askme/css/bootstrap-reboot.min.css" %}">
    <title>Hasker</title>
</head>
<body>
    <div class="container">

        <nav class="navbar navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'askme:index' %}">Hasker</a>
            <form action="{% url 'askme:search' %}" method="get" class="form-inline" accept-charset="utf-8">
                <div class="input-group">
                    <button class="input-group-addon" type="submit">Search</button>
                    <input class="form-control"
                           type="text"
                           aria-label="Search"
                           name="q"
                           placeholder="Text or tag name..."
                           value="{% if search_query %} {{ search_query }} {% endif %}">
                </div>
            </form>
            {% if user.is_authenticated %}
                <div>
                    <img src="{{ user.photo_url }}" alt="" height="50px">
                    <a href="{% url 'hasker_user:settings' %}">{{ user.username }}</a>
                    <a href="{% url 'hasker_user:logout' %}">
                        <img src="{% static 'askme/img/exit.png' %}" alt="">
                    </a>
                </div>
            {% else %}
                <div>
                    <a href="{% url 'hasker_user:login' %}">Log In</a>
                    <a class="btn btn-secondary" href="{% url 'hasker_user:signup' %}" role="button">Sign Up</a>
                </div>
            {% endif %}
        </nav>

        <hr>

        <div class="row">
            <div class="col-sm-10">
                {% block content %}{% endblock content %}
            </div>
            <div class="col">
                {% if user.is_authenticated and not hide_ask_btn %}
                    <a class="btn btn-secondary btn-block" role="button" href="{% url 'askme:ask' %}">Ask</a>
                {% endif %}
                <br>
                <h2>Trending</h2>
                {% for top in top_questions %}
                    <p>
                        <a href="{% url 'askme:question' top.slug %}" class="badge badge-primary">{{ top.votes }}</a>
                        {{ top.title }}
                    </p>
                {% endfor %}
            </div>
        </div>
    </div>

    <script src="{% static "askme/js/jquery-3.2.1.slim.min.js" %}"></script>
    <script src="{% static "askme/js/popper.min.js" %}"></script>
    <script src="{% static "askme/js/bootstrap.min.js" %}"></script>
    <script src="{% static "askme/js/bootstrap.bundle.min.js" %}"></script>

    {% block script %}{% endblock script %}
</body>
</html>

hw6/hasker/askme/templates/askme/index.html
{% extends "askme/base.html" %}

{% block content %}
    <span class="h2">New questions |</span><span class="h2 text-muted">Hot questions</span>
    <hr>
    {% for question in questions %}
        {% include "askme/answer_row.html" with question=question %}
    {% endfor %}
    {% include "askme/paging.html" with list_page=questions %}
{% endblock content %}

hw6/hasker/askme/templates/askme/paging.html
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-end">
        {% if list_page.number != 1 %}
            <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
            <li class="page-item">
                <a class="page-link active"
                   href="?page={{ list_page.previous_page_number }}">{{ list_page.previous_page_number }}</a>
            </li>
        {% endif %}
        {% if list_page.has_other_pages %}
            <li class="page-item active">
                <a class="page-link" href="?page={{ list_page.number }}">{{ list_page.number }}</a>
            </li>
        {% endif %}
        {% if list_page.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ list_page.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>
</nav>

hw6/hasker/askme/templates/askme/question.html
{% extends "askme/base.html" %}

{% block content %}
{#  Вопрос  #}
    <h4>{{ question.title }}</h4>
    <div class="row">
        <div class="col col-md-1">
            <div onclick="vote('question','up',{{ question.pk }},this)">+</div>
            <div class="votes">{{ question.votes }}</div>
            <div onclick="vote('question','down',{{ question.pk }},this)">-</div>
        </div>
        <div class="col">{{ question.text }}</div>
    </div>
    <div class="row">
        <div class="col col-md-1"></div>
        <div class="col">
            {% for tag in question.tags.all %}
                <a class="badge badge-primary" role="button" href="{% url 'askme:search_tag' tag.name %}">{{ tag.name }}</a>
            {% endfor %}
        </div>
        <div class="col col-md-2">
            <img src="{{ question.user.photo_url }}" alt="" height="30px">
            <span>{{ question.user.username }}</span>
        </div>
    </div>
    <hr>

{#    Ответы  #}
    {% for answer in answers %}
        <div class="row">
            <div class="col col-md-1">
                <div class="answer-vote-up" onclick="vote('answer','up',{{ answer.pk }},this)">+</div>
                <div class="votes">{{ answer.votes }}</div>
                <div class="answer-vote-down" onclick="vote('answer','down',{{ answer.pk }},this)">-</div>
                <div onclick="set_correct_answer({{ answer.pk }},this)">SET</div>
            </div>
            <div class="col">{{ answer.text }}</div>
        </div>
        <div class="row">
            <div class="col col-md-1"></div>
            <div class="col"></div>
            <div class="col col-md-2">
                <img src="{{ user.photo_url }}" alt="" height="30px">
                <span>{{ question.user.username }}</span>
            </div>
        </div>
        <hr>
    {% endfor %}

    {% include "askme/paging.html" with list_page=answers %}

{#    Добавить ответ   #}
    {% if user.is_authenticated %}
        <h4>Your answer</h4>
        <div class="row">
            <div class="col col-md-1"></div>
            <div class="col">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="answerForm"></label>
                        <textarea class="form-control" name="text" id="answerForm" rows="10"></textarea>
                    </div>
                    <button class="btn btn-secondary" type="submit">Submit</button>
                </form>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block script %}
<script>
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var csrftoken = getCookie('csrftoken');
    var apiURL = {
        answer: {
            up: '/api_common/answer/voteup/',
            down: '/api_common/answer/votedown/',
            set_correct: '/api_common/answer/setcorrect/'
        },
        question: {
            up: '/api_common/question/voteup/',
            down: '/api_common/question/votedown/'
        }
    };

    function vote(subject, up_or_down, id, elem) {
        var url = apiURL[subject][up_or_down] + id + '/';
        $.post({
            url: url,
            beforeSend: function(xhr) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            },
            success: function (data) {
                $(elem).siblings('.votes').text(data);
            }
        });
    }

    function set_correct_answer(id, elem) {
        var url = apiURL['answer']['set_correct'] + id + '/';
        $.post({
            url: url,
            beforeSend: function(xhr) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            },
            success: function (data) {
                $(elem).text('TRUE');
            }
        });
    }
</script>
{% endblock %}

hw6/hasker/askme/templates/askme/search.html
{% extends 'askme/index.html' %}

{% block content %}
    <h4>{{ head_title }}</h4>
    <hr>
    {% for question in questions %}
        {% include "askme/answer_row.html" with question=question %}
    {% endfor %}
    {% include "askme/paging.html" with list_page=questions %}
{% endblock content %}